"""Collection of derivative pricing models."""

from .base import DerivativeModel

# flake8: noqa

from .constant_debt_to_equity import ConstantDebtToEquity
from .credit_basket_linear import CreditBasketLinear
from .zero_coupon import ZeroCoupon
from .price_curve import PriceCurve
from .commodity_asian_option import CommodityAsianOption
from .hazard_rate_model import HazardRateModel
from .synthetic_underlying_forward import SyntheticUnderlyingForward
from .theoretical_dividend_futures import TheoreticalDividendFutures
from .underlying_spot import UnderlyingSpot
from .asian_arithmetic_fix_mm import AsianArithmeticFixMM
from .theoretical_simple_dividend_option import TheoreticalSimpleDividendOption
from .total_return_swap import TotalReturnSwap
from .qedi_variable_strike_warrant import QEDIVariableStrikeWarrant
from .convexity_adjusted_interest_rate_futures import ConvexityAdjustedInterestRateFutures
from .barrier_continuous_analytic import BarrierContinuousAnalytic
from .discretised_barrier import DiscretisedBarrier
from .index_linked_bond_forward import IndexLinkedBondForward
from .fund_instrument import FundInstrument
from .corporate_bond_model import CorporateBondModel
from .theoretical_dividend_neutral_futures import TheoreticalDividendNeutralFutures
from .udmc_cliquet_model import UDMCCliquetModel
from .fully_funded_trs import FullyFundedTRS
from .finite_difference import FiniteDifference
from .simple_tradeable_deposit import SimpleTradeableDeposit
